import dotenv from "dotenv";
import { createReadStream } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import csv from "csv-parser";
import { disconnect } from "mongoose";
import MatchActive from "../../models/matchActive.model.js";
import connectDB from "../../config/db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config({ path: join(__dirname, "../../.env") });

const toNumber = (val) => {
  const num = Number(val?.trim());
  return isNaN(num) ? undefined : num;
};

const toDate = (val) => {
  const d = new Date(val?.trim());
  return isNaN(d.getTime()) ? undefined : d;
};

const BATCH_SIZE = 100;

const importMatchesActive = async () => {
  try {
    await connectDB();
    console.log("📡 Connected to DB");

    const filePath = join(__dirname, "data", "matchActive.csv");
    const readStream = createReadStream(filePath).pipe(csv());

    const batch = [];
    let totalInserted = 0;

    for await (const data of readStream) {
      console.log(data.player1TPId);
      const matchActive = {
        _id: toNumber(data.matchTPId),
        tournamentEventTPId: toNumber(data.tournamentEventTPId),
        dateTime: toDate(data.dateTime),
        player1TPId: toNumber(data.player1TPId),
        player2TPId: toNumber(data.player2TPId),
        player1Seed: data.player1Seed,
        player2Seed: data.player2Seed,
        player1Odds: toNumber(data.player1Odds),
        player2Odds: toNumber(data.player2Odds),
        player1Percentage: toNumber(data.player1Percentage),
        player2Percentage: toNumber(data.player2Percentage),
        surfaceId: toNumber(data.surfaceId),
        player1TrueSkillMeanOldM: toNumber(data.player1TrueSkillMeanOldM),
        player1TrueSkillStandardDeviationOldM: toNumber(data.player1TrueSkillStandardDeviationOldM),
        player2TrueSkillMeanOldM: toNumber(data.player2TrueSkillMeanOldM),
        player2TrueSkillStandardDeviationOldM: toNumber(data.player2TrueSkillStandardDeviationOldM),
        winProbabilityPlayer1M: toNumber(data.winProbabilityPlayer1M),
        player1TrueSkillMeanOldSM: toNumber(data.player1TrueSkillMeanOldSM),
        player1TrueSkillStandardDeviationOldSM: toNumber(data.player1TrueSkillStandardDeviationOldSM),
        player2TrueSkillMeanOldSM: toNumber(data.player2TrueSkillMeanOldSM),
        player2TrueSkillStandardDeviationOldSM: toNumber(data.player2TrueSkillStandardDeviationOldSM),
        winProbabilityPlayer1SM: toNumber(data.winProbabilityPlayer1SM),
        player1TrueSkillMeanOldGSM: toNumber(data.player1TrueSkillMeanOldGSM),
        player1TrueSkillStandardDeviationOldGSM: toNumber(data.player1TrueSkillStandardDeviationOldGSM),
        player2TrueSkillMeanOldGSM: toNumber(data.player2TrueSkillMeanOldGSM),
        player2TrueSkillStandardDeviationOldGSM: toNumber(data.player2TrueSkillStandardDeviationOldGSM),
        winProbabilityPlayer1GSM: toNumber(data.winProbabilityPlayer1GSM),
        player1TrueSkillMeanOldMS1: toNumber(data.player1TrueSkillMeanOldMS1),
        player1TrueSkillStandardDeviationOldMS1: toNumber(data.player1TrueSkillStandardDeviationOldMS1),
        player2TrueSkillMeanOldMS1: toNumber(data.player2TrueSkillMeanOldMS1),
        player2TrueSkillStandardDeviationOldMS1: toNumber(data.player2TrueSkillStandardDeviationOldMS1),
        winProbabilityPlayer1MS1: toNumber(data.winProbabilityPlayer1MS1),
        player1TrueSkillMeanOldSMS1: toNumber(data.player1TrueSkillMeanOldSMS1),
        player1TrueSkillStandardDeviationOldSMS1: toNumber(data.player1TrueSkillStandardDeviationOldSMS1),
        player2TrueSkillMeanOldSMS1: toNumber(data.player2TrueSkillMeanOldSMS1),
        player2TrueSkillStandardDeviationOldSMS1: toNumber(data.player2TrueSkillStandardDeviationOldSMS1),
        winProbabilityPlayer1SMS1: toNumber(data.winProbabilityPlayer1SMS1),
        player1TrueSkillMeanOldGSMS1: toNumber(data.player1TrueSkillMeanOldGSMS1),
        player1TrueSkillStandardDeviationOldGSMS1: toNumber(data.player1TrueSkillStandardDeviationOldGSMS1),
        player2TrueSkillMeanOldGSMS1: toNumber(data.player2TrueSkillMeanOldGSMS1),
        player2TrueSkillStandardDeviationOldGSMS1: toNumber(data.player2TrueSkillStandardDeviationOldGSMS1),
        winProbabilityPlayer1GSMS1: toNumber(data.winProbabilityPlayer1GSMS1),
        player1TrueSkillMeanOldMS2: toNumber(data.player1TrueSkillMeanOldMS2),
        player1TrueSkillStandardDeviationOldMS2: toNumber(data.player1TrueSkillStandardDeviationOldMS2),
        player2TrueSkillMeanOldMS2: toNumber(data.player2TrueSkillMeanOldMS2),
        player2TrueSkillStandardDeviationOldMS2: toNumber(data.player2TrueSkillStandardDeviationOldMS2),
        winProbabilityPlayer1MS2: toNumber(data.winProbabilityPlayer1MS2),
        player1TrueSkillMeanOldSMS2: toNumber(data.player1TrueSkillMeanOldSMS2),
        player1TrueSkillStandardDeviationOldSMS2: toNumber(data.player1TrueSkillStandardDeviationOldSMS2),
        player2TrueSkillMeanOldSMS2: toNumber(data.player2TrueSkillMeanOldSMS2),
        player2TrueSkillStandardDeviationOldSMS2: toNumber(data.player2TrueSkillStandardDeviationOldSMS2),
        winProbabilityPlayer1SMS2: toNumber(data.winProbabilityPlayer1SMS2),
        player1TrueSkillMeanOldGSMS2: toNumber(data.player1TrueSkillMeanOldGSMS2),
        player1TrueSkillStandardDeviationOldGSMS2: toNumber(data.player1TrueSkillStandardDeviationOldGSMS2),
        player2TrueSkillMeanOldGSMS2: toNumber(data.player2TrueSkillMeanOldGSMS2),
        player2TrueSkillStandardDeviationOldGSMS2: toNumber(data.player2TrueSkillStandardDeviationOldGSMS2),
        winProbabilityPlayer1GSMS2: toNumber(data.winProbabilityPlayer1GSMS2),
        player1TrueSkillMeanOldMS3: toNumber(data.player1TrueSkillMeanOldMS3),
        player1TrueSkillStandardDeviationOldMS3: toNumber(data.player1TrueSkillStandardDeviationOldMS3),
        player2TrueSkillMeanOldMS3: toNumber(data.player2TrueSkillMeanOldMS3),
        player2TrueSkillStandardDeviationOldMS3: toNumber(data.player2TrueSkillStandardDeviationOldMS3),
        winProbabilityPlayer1MS3: toNumber(data.winProbabilityPlayer1MS3),
        player1TrueSkillMeanOldSMS3: toNumber(data.player1TrueSkillMeanOldSMS3),
        player1TrueSkillStandardDeviationOldSMS3: toNumber(data.player1TrueSkillStandardDeviationOldSMS3),
        player2TrueSkillMeanOldSMS3: toNumber(data.player2TrueSkillMeanOldSMS3),
        player2TrueSkillStandardDeviationOldSMS3: toNumber(data.player2TrueSkillStandardDeviationOldSMS3),
        winProbabilityPlayer1SMS3: toNumber(data.winProbabilityPlayer1SMS3),
        player1TrueSkillMeanOldGSMS3: toNumber(data.player1TrueSkillMeanOldGSMS3),
        player1TrueSkillStandardDeviationOldGSMS3: toNumber(data.player1TrueSkillStandardDeviationOldGSMS3),
        player2TrueSkillMeanOldGSMS3: toNumber(data.player2TrueSkillMeanOldGSMS3),
        player2TrueSkillStandardDeviationOldGSMS3: toNumber(data.player2TrueSkillStandardDeviationOldGSMS3),
        winProbabilityPlayer1GSMS3: toNumber(data.winProbabilityPlayer1GSMS3),
        player1TrueSkillMeanOldMS4: toNumber(data.player1TrueSkillMeanOldMS4),
        player1TrueSkillStandardDeviationOldMS4: toNumber(data.player1TrueSkillStandardDeviationOldMS4),
        player2TrueSkillMeanOldMS4: toNumber(data.player2TrueSkillMeanOldMS4),
        player2TrueSkillStandardDeviationOldMS4: toNumber(data.player2TrueSkillStandardDeviationOldMS4),
        winProbabilityPlayer1MS4: toNumber(data.winProbabilityPlayer1MS4),
        player1TrueSkillMeanOldSMS4: toNumber(data.player1TrueSkillMeanOldSMS4),
        player1TrueSkillStandardDeviationOldSMS4: toNumber(data.player1TrueSkillStandardDeviationOldSMS4),
        player2TrueSkillMeanOldSMS4: toNumber(data.player2TrueSkillMeanOldSMS4),
        player2TrueSkillStandardDeviationOldSMS4: toNumber(data.player2TrueSkillStandardDeviationOldSMS4),
        winProbabilityPlayer1SMS4: toNumber(data.winProbabilityPlayer1SMS4),
        player1TrueSkillMeanOldGSMS4: toNumber(data.player1TrueSkillMeanOldGSMS4),
        player1TrueSkillStandardDeviationOldGSMS4: toNumber(data.player1TrueSkillStandardDeviationOldGSMS4),
        player2TrueSkillMeanOldGSMS4: toNumber(data.player2TrueSkillMeanOldGSMS4),
        player2TrueSkillStandardDeviationOldGSMS4: toNumber(data.player2TrueSkillStandardDeviationOldGSMS4),
        winProbabilityPlayer1GSMS4: toNumber(data.winProbabilityPlayer1GSMS4),
        player1WinsTotal: toNumber(data.player1WinsTotal),
        player1LossesTotal: toNumber(data.player1LossesTotal),
        player1WinsLastYear: toNumber(data.player1WinsLastYear),
        player1LossesLastYear: toNumber(data.player1LossesLastYear),
        player1WinsLastMonth: toNumber(data.player1WinsLastMonth),
        player1LossesLastMonth: toNumber(data.player1LossesLastMonth),
        player1WinsLastWeek: toNumber(data.player1WinsLastWeek),
        player1LossesLastWeek: toNumber(data.player1LossesLastWeek),
        player2WinsTotal: toNumber(data.player2WinsTotal),
        player2LossesTotal: toNumber(data.player2LossesTotal),
        player2WinsLastYear: toNumber(data.player2WinsLastYear),
        player2LossesLastYear: toNumber(data.player2LossesLastYear),
        player2WinsLastMonth: toNumber(data.player2WinsLastMonth),
        player2LossesLastMonth: toNumber(data.player2LossesLastMonth),
        player2WinsLastWeek: toNumber(data.player2WinsLastWeek),
        player2LossesLastWeek: toNumber(data.player2LossesLastWeek),
        player1WinsTotalS1: toNumber(data.player1WinsTotalS1),
        player1LossesTotalS1: toNumber(data.player1LossesTotalS1),
        player1WinsLastYearS1: toNumber(data.player1WinsLastYearS1),
        player1LossesLastYearS1: toNumber(data.player1LossesLastYearS1),
        player1WinsLastMonthS1: toNumber(data.player1WinsLastMonthS1),
        player1LossesLastMonthS1: toNumber(data.player1LossesLastMonthS1),
        player1WinsLastWeekS1: toNumber(data.player1WinsLastWeekS1),
        player1LossesLastWeekS1: toNumber(data.player1LossesLastWeekS1),
        player2WinsTotalS1: toNumber(data.player2WinsTotalS1),
        player2LossesTotalS1: toNumber(data.player2LossesTotalS1),
        player2WinsLastYearS1: toNumber(data.player2WinsLastYearS1),
        player2LossesLastYearS1: toNumber(data.player2LossesLastYearS1),
        player2WinsLastMonthS1: toNumber(data.player2WinsLastMonthS1),
        player2LossesLastMonthS1: toNumber(data.player2LossesLastMonthS1),
        player2WinsLastWeekS1: toNumber(data.player2WinsLastWeekS1),
        player2LossesLastWeekS1: toNumber(data.player2LossesLastWeekS1),
        player1WinsTotalS2: toNumber(data.player1WinsTotalS2),
        player1LossesTotalS2: toNumber(data.player1LossesTotalS2),
        player1WinsLastYearS2: toNumber(data.player1WinsLastYearS2),
        player1LossesLastYearS2: toNumber(data.player1LossesLastYearS2),
        player1WinsLastMonthS2: toNumber(data.player1WinsLastMonthS2),
        player1LossesLastMonthS2: toNumber(data.player1LossesLastMonthS2),
        player1WinsLastWeekS2: toNumber(data.player1WinsLastWeekS2),
        player1LossesLastWeekS2: toNumber(data.player1LossesLastWeekS2),
        player2WinsTotalS2: toNumber(data.player2WinsTotalS2),
        player2LossesTotalS2: toNumber(data.player2LossesTotalS2),
        player2WinsLastYearS2: toNumber(data.player2WinsLastYearS2),
        player2LossesLastYearS2: toNumber(data.player2LossesLastYearS2),
        player2WinsLastMonthS2: toNumber(data.player2WinsLastMonthS2),
        player2LossesLastMonthS2: toNumber(data.player2LossesLastMonthS2),
        player2WinsLastWeekS2: toNumber(data.player2WinsLastWeekS2),
        player2LossesLastWeekS2: toNumber(data.player2LossesLastWeekS2),
        player1WinsTotalS3: toNumber(data.player1WinsTotalS3),
        player1LossesTotalS3: toNumber(data.player1LossesTotalS3),
        player1WinsLastYearS3: toNumber(data.player1WinsLastYearS3),
        player1LossesLastYearS3: toNumber(data.player1LossesLastYearS3),
        player1WinsLastMonthS3: toNumber(data.player1WinsLastMonthS3),
        player1LossesLastMonthS3: toNumber(data.player1LossesLastMonthS3),
        player1WinsLastWeekS3: toNumber(data.player1WinsLastWeekS3),
        player1LossesLastWeekS3: toNumber(data.player1LossesLastWeekS3),
        player2WinsTotalS3: toNumber(data.player2WinsTotalS3),
        player2LossesTotalS3: toNumber(data.player2LossesTotalS3),
        player2WinsLastYearS3: toNumber(data.player2WinsLastYearS3),
        player2LossesLastYearS3: toNumber(data.player2LossesLastYearS3),
        player2WinsLastMonthS3: toNumber(data.player2WinsLastMonthS3),
        player2LossesLastMonthS3: toNumber(data.player2LossesLastMonthS3),
        player2WinsLastWeekS3: toNumber(data.player2WinsLastWeekS3),
        player2LossesLastWeekS3: toNumber(data.player2LossesLastWeekS3),
        player1WinsTotalS4: toNumber(data.player1WinsTotalS4),
        player1LossesTotalS4: toNumber(data.player1LossesTotalS4),
        player1WinsLastYearS4: toNumber(data.player1WinsLastYearS4),
        player1LossesLastYearS4: toNumber(data.player1LossesLastYearS4),
        player1WinsLastMonthS4: toNumber(data.player1WinsLastMonthS4),
        player1LossesLastMonthS4: toNumber(data.player1LossesLastMonthS4),
        player1WinsLastWeekS4: toNumber(data.player1WinsLastWeekS4),
        player1LossesLastWeekS4: toNumber(data.player1LossesLastWeekS4),
        player2WinsTotalS4: toNumber(data.player2WinsTotalS4),
        player2LossesTotalS4: toNumber(data.player2LossesTotalS4),
        player2WinsLastYearS4: toNumber(data.player2WinsLastYearS4),
        player2LossesLastYearS4: toNumber(data.player2LossesLastYearS4),
        player2WinsLastMonthS4: toNumber(data.player2WinsLastMonthS4),
        player2LossesLastMonthS4: toNumber(data.player2LossesLastMonthS4),
        player2WinsLastWeekS4: toNumber(data.player2WinsLastWeekS4),
        player2LossesLastWeekS4: toNumber(data.player2LossesLastWeekS4),
        player1WinsSetsTotal: toNumber(data.player1WinsSetsTotal),
        player1LossesSetsTotal: toNumber(data.player1LossesSetsTotal),
        player1WinsSetsLastYear: toNumber(data.player1WinsSetsLastYear),
        player1LossesSetsLastYear: toNumber(data.player1LossesSetsLastYear),
        player1WinsSetsLastMonth: toNumber(data.player1WinsSetsLastMonth),
        player1LossesSetsLastMonth: toNumber(data.player1LossesSetsLastMonth),
        player1WinsSetsLastWeek: toNumber(data.player1WinsSetsLastWeek),
        player1LossesSetsLastWeek: toNumber(data.player1LossesSetsLastWeek),
        player2WinsSetsTotal: toNumber(data.player2WinsSetsTotal),
        player2LossesSetsTotal: toNumber(data.player2LossesSetsTotal),
        player2WinsSetsLastYear: toNumber(data.player2WinsSetsLastYear),
        player2LossesSetsLastYear: toNumber(data.player2LossesSetsLastYear),
        player2WinsSetsLastMonth: toNumber(data.player2WinsSetsLastMonth),
        player2LossesSetsLastMonth: toNumber(data.player2LossesSetsLastMonth),
        player2WinsSetsLastWeek: toNumber(data.player2WinsSetsLastWeek),
        player2LossesSetsLastWeek: toNumber(data.player2LossesSetsLastWeek),
        player1WinsSetsTotalS1: toNumber(data.player1WinsSetsTotalS1),
        player1LossesSetsTotalS1: toNumber(data.player1LossesSetsTotalS1),
        player1WinsSetsLastYearS1: toNumber(data.player1WinsSetsLastYearS1),
        player1LossesSetsLastYearS1: toNumber(data.player1LossesSetsLastYearS1),
        player1WinsSetsLastMonthS1: toNumber(data.player1WinsSetsLastMonthS1),
        player1LossesSetsLastMonthS1: toNumber(data.player1LossesSetsLastMonthS1),
        player1WinsSetsLastWeekS1: toNumber(data.player1WinsSetsLastWeekS1),
        player1LossesSetsLastWeekS1: toNumber(data.player1LossesSetsLastWeekS1),
        player2WinsSetsTotalS1: toNumber(data.player2WinsSetsTotalS1),
        player2LossesSetsTotalS1: toNumber(data.player2LossesSetsTotalS1),
        player2WinsSetsLastYearS1: toNumber(data.player2WinsSetsLastYearS1),
        player2LossesSetsLastYearS1: toNumber(data.player2LossesSetsLastYearS1),
        player2WinsSetsLastMonthS1: toNumber(data.player2WinsSetsLastMonthS1),
        player2LossesSetsLastMonthS1: toNumber(data.player2LossesSetsLastMonthS1),
        player2WinsSetsLastWeekS1: toNumber(data.player2WinsSetsLastWeekS1),
        player2LossesSetsLastWeekS1: toNumber(data.player2LossesSetsLastWeekS1),
        player1WinsSetsTotalS2: toNumber(data.player1WinsSetsTotalS2),
        player1LossesSetsTotalS2: toNumber(data.player1LossesSetsTotalS2),
        player1WinsSetsLastYearS2: toNumber(data.player1WinsSetsLastYearS2),
        player1LossesSetsLastYearS2: toNumber(data.player1LossesSetsLastYearS2),
        player1WinsSetsLastMonthS2: toNumber(data.player1WinsSetsLastMonthS2),
        player1LossesSetsLastMonthS2: toNumber(data.player1LossesSetsLastMonthS2),
        player1WinsSetsLastWeekS2: toNumber(data.player1WinsSetsLastWeekS2),
        player1LossesSetsLastWeekS2: toNumber(data.player1LossesSetsLastWeekS2),
        player2WinsSetsTotalS2: toNumber(data.player2WinsSetsTotalS2),
        player2LossesSetsTotalS2: toNumber(data.player2LossesSetsTotalS2),
        player2WinsSetsLastYearS2: toNumber(data.player2WinsSetsLastYearS2),
        player2LossesSetsLastYearS2: toNumber(data.player2LossesSetsLastYearS2),
        player2WinsSetsLastMonthS2: toNumber(data.player2WinsSetsLastMonthS2),
        player2LossesSetsLastMonthS2: toNumber(data.player2LossesSetsLastMonthS2),
        player2WinsSetsLastWeekS2: toNumber(data.player2WinsSetsLastWeekS2),
        player2LossesSetsLastWeekS2: toNumber(data.player2LossesSetsLastWeekS2),
        player1WinsSetsTotalS3: toNumber(data.player1WinsSetsTotalS3),
        player1LossesSetsTotalS3: toNumber(data.player1LossesSetsTotalS3),
        player1WinsSetsLastYearS3: toNumber(data.player1WinsSetsLastYearS3),
        player1LossesSetsLastYearS3: toNumber(data.player1LossesSetsLastYearS3),
        player1WinsSetsLastMonthS3: toNumber(data.player1WinsSetsLastMonthS3),
        player1LossesSetsLastMonthS3: toNumber(data.player1LossesSetsLastMonthS3),
        player1WinsSetsLastWeekS3: toNumber(data.player1WinsSetsLastWeekS3),
        player1LossesSetsLastWeekS3: toNumber(data.player1LossesSetsLastWeekS3),
        player2WinsSetsTotalS3: toNumber(data.player2WinsSetsTotalS3),
        player2LossesSetsTotalS3: toNumber(data.player2LossesSetsTotalS3),
        player2WinsSetsLastYearS3: toNumber(data.player2WinsSetsLastYearS3),
        player2LossesSetsLastYearS3: toNumber(data.player2LossesSetsLastYearS3),
        player2WinsSetsLastMonthS3: toNumber(data.player2WinsSetsLastMonthS3),
        player2LossesSetsLastMonthS3: toNumber(data.player2LossesSetsLastMonthS3),
        player2WinsSetsLastWeekS3: toNumber(data.player2WinsSetsLastWeekS3),
        player2LossesSetsLastWeekS3: toNumber(data.player2LossesSetsLastWeekS3),
        player1WinsSetsTotalS4: toNumber(data.player1WinsSetsTotalS4),
        player1LossesSetsTotalS4: toNumber(data.player1LossesSetsTotalS4),
        player1WinsSetsLastYearS4: toNumber(data.player1WinsSetsLastYearS4),
        player1LossesSetsLastYearS4: toNumber(data.player1LossesSetsLastYearS4),
        player1WinsSetsLastMonthS4: toNumber(data.player1WinsSetsLastMonthS4),
        player1LossesSetsLastMonthS4: toNumber(data.player1LossesSetsLastMonthS4),
        player1WinsSetsLastWeekS4: toNumber(data.player1WinsSetsLastWeekS4),
        player1LossesSetsLastWeekS4: toNumber(data.player1LossesSetsLastWeekS4),
        player2WinsSetsTotalS4: toNumber(data.player2WinsSetsTotalS4),
        player2LossesSetsTotalS4: toNumber(data.player2LossesSetsTotalS4),
        player2WinsSetsLastYearS4: toNumber(data.player2WinsSetsLastYearS4),
        player2LossesSetsLastYearS4: toNumber(data.player2LossesSetsLastYearS4),
        player2WinsSetsLastMonthS4: toNumber(data.player2WinsSetsLastMonthS4),
        player2LossesSetsLastMonthS4: toNumber(data.player2LossesSetsLastMonthS4),
        player2WinsSetsLastWeekS4: toNumber(data.player2WinsSetsLastWeekS4),
        player2LossesSetsLastWeekS4: toNumber(data.player2LossesSetsLastWeekS4),
        player1WinsGamesTotal: toNumber(data.player1WinsGamesTotal),
        player1LossesGamesTotal: toNumber(data.player1LossesGamesTotal),
        player1WinsGamesLastYear: toNumber(data.player1WinsGamesLastYear),
        player1LossesGamesLastYear: toNumber(data.player1LossesGamesLastYear),
        player1WinsGamesLastMonth: toNumber(data.player1WinsGamesLastMonth),
        player1LossesGamesLastMonth: toNumber(data.player1LossesGamesLastMonth),
        player1WinsGamesLastWeek: toNumber(data.player1WinsGamesLastWeek),
        player1LossesGamesLastWeek: toNumber(data.player1LossesGamesLastWeek),
        player2WinsGamesTotal: toNumber(data.player2WinsGamesTotal),
        player2LossesGamesTotal: toNumber(data.player2LossesGamesTotal),
        player2WinsGamesLastYear: toNumber(data.player2WinsGamesLastYear),
        player2LossesGamesLastYear: toNumber(data.player2LossesGamesLastYear),
        player2WinsGamesLastMonth: toNumber(data.player2WinsGamesLastMonth),
        player2LossesGamesLastMonth: toNumber(data.player2LossesGamesLastMonth),
        player2WinsGamesLastWeek: toNumber(data.player2WinsGamesLastWeek),
        player2LossesGamesLastWeek: toNumber(data.player2LossesGamesLastWeek),
        player1WinsGamesTotalS1: toNumber(data.player1WinsGamesTotalS1),
        player1LossesGamesTotalS1: toNumber(data.player1LossesGamesTotalS1),
        player1WinsGamesLastYearS1: toNumber(data.player1WinsGamesLastYearS1),
        player1LossesGamesLastYearS1: toNumber(data.player1LossesGamesLastYearS1),
        player1WinsGamesLastMonthS1: toNumber(data.player1WinsGamesLastMonthS1),
        player1LossesGamesLastMonthS1: toNumber(data.player1LossesGamesLastMonthS1),
        player1WinsGamesLastWeekS1: toNumber(data.player1WinsGamesLastWeekS1),
        player1LossesGamesLastWeekS1: toNumber(data.player1LossesGamesLastWeekS1),
        player2WinsGamesTotalS1: toNumber(data.player2WinsGamesTotalS1),
        player2LossesGamesTotalS1: toNumber(data.player2LossesGamesTotalS1),
        player2WinsGamesLastYearS1: toNumber(data.player2WinsGamesLastYearS1),
        player2LossesGamesLastYearS1: toNumber(data.player2LossesGamesLastYearS1),
        player2WinsGamesLastMonthS1: toNumber(data.player2WinsGamesLastMonthS1),
        player2LossesGamesLastMonthS1: toNumber(data.player2LossesGamesLastMonthS1),
        player2WinsGamesLastWeekS1: toNumber(data.player2WinsGamesLastWeekS1),
        player2LossesGamesLastWeekS1: toNumber(data.player2LossesGamesLastWeekS1),
        player1WinsGamesTotalS2: toNumber(data.player1WinsGamesTotalS2),
        player1LossesGamesTotalS2: toNumber(data.player1LossesGamesTotalS2),
        player1WinsGamesLastYearS2: toNumber(data.player1WinsGamesLastYearS2),
        player1LossesGamesLastYearS2: toNumber(data.player1LossesGamesLastYearS2),
        player1WinsGamesLastMonthS2: toNumber(data.player1WinsGamesLastMonthS2),
        player1LossesGamesLastMonthS2: toNumber(data.player1LossesGamesLastMonthS2),
        player1WinsGamesLastWeekS2: toNumber(data.player1WinsGamesLastWeekS2),
        player1LossesGamesLastWeekS2: toNumber(data.player1LossesGamesLastWeekS2),
        player2WinsGamesTotalS2: toNumber(data.player2WinsGamesTotalS2),
        player2LossesGamesTotalS2: toNumber(data.player2LossesGamesTotalS2),
        player2WinsGamesLastYearS2: toNumber(data.player2WinsGamesLastYearS2),
        player2LossesGamesLastYearS2: toNumber(data.player2LossesGamesLastYearS2),
        player2WinsGamesLastMonthS2: toNumber(data.player2WinsGamesLastMonthS2),
        player2LossesGamesLastMonthS2: toNumber(data.player2LossesGamesLastMonthS2),
        player2WinsGamesLastWeekS2: toNumber(data.player2WinsGamesLastWeekS2),
        player2LossesGamesLastWeekS2: toNumber(data.player2LossesGamesLastWeekS2),
        player1WinsGamesTotalS3: toNumber(data.player1WinsGamesTotalS3),
        player1LossesGamesTotalS3: toNumber(data.player1LossesGamesTotalS3),
        player1WinsGamesLastYearS3: toNumber(data.player1WinsGamesLastYearS3),
        player1LossesGamesLastYearS3: toNumber(data.player1LossesGamesLastYearS3),
        player1WinsGamesLastMonthS3: toNumber(data.player1WinsGamesLastMonthS3),
        player1LossesGamesLastMonthS3: toNumber(data.player1LossesGamesLastMonthS3),
        player1WinsGamesLastWeekS3: toNumber(data.player1WinsGamesLastWeekS3),
        player1LossesGamesLastWeekS3: toNumber(data.player1LossesGamesLastWeekS3),
        player2WinsGamesTotalS3: toNumber(data.player2WinsGamesTotalS3),
        player2LossesGamesTotalS3: toNumber(data.player2LossesGamesTotalS3),
        player2WinsGamesLastYearS3: toNumber(data.player2WinsGamesLastYearS3),
        player2LossesGamesLastYearS3: toNumber(data.player2LossesGamesLastYearS3),
        player2WinsGamesLastMonthS3: toNumber(data.player2WinsGamesLastMonthS3),
        player2LossesGamesLastMonthS3: toNumber(data.player2LossesGamesLastMonthS3),
        player2WinsGamesLastWeekS3: toNumber(data.player2WinsGamesLastWeekS3),
        player2LossesGamesLastWeekS3: toNumber(data.player2LossesGamesLastWeekS3),
        player1WinsGamesTotalS4: toNumber(data.player1WinsGamesTotalS4),
        player1LossesGamesTotalS4: toNumber(data.player1LossesGamesTotalS4),
        player1WinsGamesLastYearS4: toNumber(data.player1WinsGamesLastYearS4),
        player1LossesGamesLastYearS4: toNumber(data.player1LossesGamesLastYearS4),
        player1WinsGamesLastMonthS4: toNumber(data.player1WinsGamesLastMonthS4),
        player1LossesGamesLastMonthS4: toNumber(data.player1LossesGamesLastMonthS4),
        player1WinsGamesLastWeekS4: toNumber(data.player1WinsGamesLastWeekS4),
        player1LossesGamesLastWeekS4: toNumber(data.player1LossesGamesLastWeekS4),
        player2WinsGamesTotalS4: toNumber(data.player2WinsGamesTotalS4),
        player2LossesGamesTotalS4: toNumber(data.player2LossesGamesTotalS4),
        player2WinsGamesLastYearS4: toNumber(data.player2WinsGamesLastYearS4),
        player2LossesGamesLastYearS4: toNumber(data.player2LossesGamesLastYearS4),
        player2WinsGamesLastMonthS4: toNumber(data.player2WinsGamesLastMonthS4),
        player2LossesGamesLastMonthS4: toNumber(data.player2LossesGamesLastMonthS4),
        player2WinsGamesLastWeekS4: toNumber(data.player2WinsGamesLastWeekS4),
        player2LossesGamesLastWeekS4: toNumber(data.player2LossesGamesLastWeekS4),
        player1DaysSinceLastWin: toNumber(data.player1DaysSinceLastWin),
        player2DaysSinceLastWin: toNumber(data.player2DaysSinceLastWin),
        player1DaysSinceLastWinS1: toNumber(data.player1DaysSinceLastWinS1),
        player2DaysSinceLastWinS1: toNumber(data.player2DaysSinceLastWinS1),
        player1DaysSinceLastWinS2: toNumber(data.player1DaysSinceLastWinS2),
        player2DaysSinceLastWinS2: toNumber(data.player2DaysSinceLastWinS2),
        player1DaysSinceLastWinS3: toNumber(data.player1DaysSinceLastWinS3),
        player2DaysSinceLastWinS3: toNumber(data.player2DaysSinceLastWinS3),
        player1DaysSinceLastWinS4: toNumber(data.player1DaysSinceLastWinS4),
        player2DaysSinceLastWinS4: toNumber(data.player2DaysSinceLastWinS4),
        player1DaysSinceLastLoss: toNumber(data.player1DaysSinceLastLoss),
        player2DaysSinceLastLoss: toNumber(data.player2DaysSinceLastLoss),
        player1DaysSinceLastLossS1: toNumber(data.player1DaysSinceLastLossS1),
        player2DaysSinceLastLossS1: toNumber(data.player2DaysSinceLastLossS1),
        player1DaysSinceLastLossS2: toNumber(data.player1DaysSinceLastLossS2),
        player2DaysSinceLastLossS2: toNumber(data.player2DaysSinceLastLossS2),
        player1DaysSinceLastLossS3: toNumber(data.player1DaysSinceLastLossS3),
        player2DaysSinceLastLossS3: toNumber(data.player2DaysSinceLastLossS3),
        player1DaysSinceLastLossS4: toNumber(data.player1DaysSinceLastLossS4),
        player2DaysSinceLastLossS4: toNumber(data.player2DaysSinceLastLossS4),
        player1TotalWinsAsFavourite: toNumber(data.player1TotalWinsAsFavourite),
        player2TotalWinsAsFavourite: toNumber(data.player2TotalWinsAsFavourite),
        player1TotalWinsAsUnderdog: toNumber(data.player1TotalWinsAsUnderdog),
        player2TotalWinsAsUnderdog: toNumber(data.player2TotalWinsAsUnderdog),
        player1TotalLossesAsFavourite: toNumber(data.player1TotalLossesAsFavourite),
        player2TotalLossesAsFavourite: toNumber(data.player2TotalLossesAsFavourite),
        player1TotalLossesAsUnderdog: toNumber(data.player1TotalLossesAsUnderdog),
        player2TotalLossesAsUnderdog: toNumber(data.player2TotalLossesAsUnderdog),
        player1AverageWinningProbabilityAtWonAsFavourite: toNumber(data.player1AverageWinningProbabilityAtWonAsFavourite),
        player2AverageWinningProbabilityAtWonAsFavourite: toNumber(data.player2AverageWinningProbabilityAtWonAsFavourite),
        player1AverageWinningProbabilityAtWonAsUnderdog: toNumber(data.player1AverageWinningProbabilityAtWonAsUnderdog),
        player2AverageWinningProbabilityAtWonAsUnderdog: toNumber(data.player2AverageWinningProbabilityAtWonAsUnderdog),
        player1AverageWinningProbabilityAtLossAsFavourite: toNumber(data.player1AverageWinningProbabilityAtLossAsFavourite),
        player2AverageWinningProbabilityAtLossAsFavourite: toNumber(data.player2AverageWinningProbabilityAtLossAsFavourite),
        player1AverageWinningProbabilityAtLossAsUnderdog: toNumber(data.player1AverageWinningProbabilityAtLossAsUnderdog),
        player2AverageWinningProbabilityAtLossAsUnderdog: toNumber(data.player2AverageWinningProbabilityAtLossAsUnderdog),
        player1TotalWinsAsFavouriteLastYear: toNumber(data.player1TotalWinsAsFavouriteLastYear),
        player2TotalWinsAsFavouriteLastYear: toNumber(data.player2TotalWinsAsFavouriteLastYear),
        player1TotalWinsAsUnderdogLastYear: toNumber(data.player1TotalWinsAsUnderdogLastYear),
        player2TotalWinsAsUnderdogLastYear: toNumber(data.player2TotalWinsAsUnderdogLastYear),
        player1TotalLossesAsFavouriteLastYear: toNumber(data.player1TotalLossesAsFavouriteLastYear),
        player2TotalLossesAsFavouriteLastYear: toNumber(data.player2TotalLossesAsFavouriteLastYear),
        player1TotalLossesAsUnderdogLastYear: toNumber(data.player1TotalLossesAsUnderdogLastYear),
        player2TotalLossesAsUnderdogLastYear: toNumber(data.player2TotalLossesAsUnderdogLastYear),
        player1AverageWinningProbabilityAtWonAsFavouriteLastYear: toNumber(data.player1AverageWinningProbabilityAtWonAsFavouriteLastYear),
        player2AverageWinningProbabilityAtWonAsFavouriteLastYear: toNumber(data.player2AverageWinningProbabilityAtWonAsFavouriteLastYear),
        player1AverageWinningProbabilityAtWonAsUnderdogLastYear: toNumber(data.player1AverageWinningProbabilityAtWonAsUnderdogLastYear),
        player2AverageWinningProbabilityAtWonAsUnderdogLastYear: toNumber(data.player2AverageWinningProbabilityAtWonAsUnderdogLastYear),
        player1AverageWinningProbabilityAtLossAsFavouriteLastYear: toNumber(data.player1AverageWinningProbabilityAtLossAsFavouriteLastYear),
        player2AverageWinningProbabilityAtLossAsFavouriteLastYear: toNumber(data.player2AverageWinningProbabilityAtLossAsFavouriteLastYear),
        player1AverageWinningProbabilityAtLossAsUnderdogLastYear: toNumber(data.player1AverageWinningProbabilityAtLossAsUnderdogLastYear),
        player2AverageWinningProbabilityAtLossAsUnderdogLastYear: toNumber(data.player2AverageWinningProbabilityAtLossAsUnderdogLastYear),
        player1TotalWinsAsFavouriteLastMonth: toNumber(data.player1TotalWinsAsFavouriteLastMonth),
        player2TotalWinsAsFavouriteLastMonth: toNumber(data.player2TotalWinsAsFavouriteLastMonth),
        player1TotalWinsAsUnderdogLastMonth: toNumber(data.player1TotalWinsAsUnderdogLastMonth),
        player2TotalWinsAsUnderdogLastMonth: toNumber(data.player2TotalWinsAsUnderdogLastMonth),
        player1TotalLossesAsFavouriteLastMonth: toNumber(data.player1TotalLossesAsFavouriteLastMonth),
        player2TotalLossesAsFavouriteLastMonth: toNumber(data.player2TotalLossesAsFavouriteLastMonth),
        player1TotalLossesAsUnderdogLastMonth: toNumber(data.player1TotalLossesAsUnderdogLastMonth),
        player2TotalLossesAsUnderdogLastMonth: toNumber(data.player2TotalLossesAsUnderdogLastMonth),
        player1AverageWinningProbabilityAtWonAsFavouriteLastMonth: toNumber(data.player1AverageWinningProbabilityAtWonAsFavouriteLastMonth),
        player2AverageWinningProbabilityAtWonAsFavouriteLastMonth: toNumber(data.player2AverageWinningProbabilityAtWonAsFavouriteLastMonth),
        player1AverageWinningProbabilityAtWonAsUnderdogLastMonth: toNumber(data.player1AverageWinningProbabilityAtWonAsUnderdogLastMonth),
        player2AverageWinningProbabilityAtWonAsUnderdogLastMonth: toNumber(data.player2AverageWinningProbabilityAtWonAsUnderdogLastMonth),
        player1AverageWinningProbabilityAtLossAsFavouriteLastMonth: toNumber(data.player1AverageWinningProbabilityAtLossAsFavouriteLastMonth),
        player2AverageWinningProbabilityAtLossAsFavouriteLastMonth: toNumber(data.player2AverageWinningProbabilityAtLossAsFavouriteLastMonth),
        player1AverageWinningProbabilityAtLossAsUnderdogLastMonth: toNumber(data.player1AverageWinningProbabilityAtLossAsUnderdogLastMonth),
        player2AverageWinningProbabilityAtLossAsUnderdogLastMonth: toNumber(data.player2AverageWinningProbabilityAtLossAsUnderdogLastMonth),
        player1TotalWinsAsFavouriteLastWeek: toNumber(data.player1TotalWinsAsFavouriteLastWeek),
        player2TotalWinsAsFavouriteLastWeek: toNumber(data.player2TotalWinsAsFavouriteLastWeek),
        player1TotalWinsAsUnderdogLastWeek: toNumber(data.player1TotalWinsAsUnderdogLastWeek),
        player2TotalWinsAsUnderdogLastWeek: toNumber(data.player2TotalWinsAsUnderdogLastWeek),
        player1TotalLossesAsFavouriteLastWeek: toNumber(data.player1TotalLossesAsFavouriteLastWeek),
        player2TotalLossesAsFavouriteLastWeek: toNumber(data.player2TotalLossesAsFavouriteLastWeek),
        player1TotalLossesAsUnderdogLastWeek: toNumber(data.player1TotalLossesAsUnderdogLastWeek),
        player2TotalLossesAsUnderdogLastWeek: toNumber(data.player2TotalLossesAsUnderdogLastWeek),
        player1AverageWinningProbabilityAtWonAsFavouriteLastWeek: toNumber(data.player1AverageWinningProbabilityAtWonAsFavouriteLastWeek),
        player2AverageWinningProbabilityAtWonAsFavouriteLastWeek: toNumber(data.player2AverageWinningProbabilityAtWonAsFavouriteLastWeek),
        player1AverageWinningProbabilityAtWonAsUnderdogLastWeek: toNumber(data.player1AverageWinningProbabilityAtWonAsUnderdogLastWeek),
        player2AverageWinningProbabilityAtWonAsUnderdogLastWeek: toNumber(data.player2AverageWinningProbabilityAtWonAsUnderdogLastWeek),
        player1AverageWinningProbabilityAtLossAsFavouriteLastWeek: toNumber(data.player1AverageWinningProbabilityAtLossAsFavouriteLastWeek),
        player2AverageWinningProbabilityAtLossAsFavouriteLastWeek: toNumber(data.player2AverageWinningProbabilityAtLossAsFavouriteLastWeek),
        player1AverageWinningProbabilityAtLossAsUnderdogLastWeek: toNumber(data.player1AverageWinningProbabilityAtLossAsUnderdogLastWeek),
        player2AverageWinningProbabilityAtLossAsUnderdogLastWeek: toNumber(data.player2AverageWinningProbabilityAtLossAsUnderdogLastWeek),
        player1H2H: toNumber(data.player1H2H),
        player2H2H: toNumber(data.player2H2H),
        player1H2HS1: toNumber(data.player1H2HS1),
        player2H2HS1: toNumber(data.player2H2HS1),
        player1H2HS2: toNumber(data.player1H2HS2),
        player2H2HS2: toNumber(data.player2H2HS2),
        player1H2HS3: toNumber(data.player1H2HS3),
        player2H2HS3: toNumber(data.player2H2HS3),
        player1H2HS4: toNumber(data.player1H2HS4),
        player2H2HS4: toNumber(data.player2H2HS4),
        player1H2HTrueSkillMeanOldM: toNumber(data.player1H2HTrueSkillMeanOldM),
        player1H2HTrueSkillStandardDeviationOldM: toNumber(data.player1H2HTrueSkillStandardDeviationOldM),
        player2H2HTrueSkillMeanOldM: toNumber(data.player2H2HTrueSkillMeanOldM),
        player2H2HTrueSkillStandardDeviationOldM: toNumber(data.player2H2HTrueSkillStandardDeviationOldM),
        winProbabilityPlayer1H2HM: toNumber(data.winProbabilityPlayer1H2HM),
        player1H2HTrueSkillMeanOldSM: toNumber(data.player1H2HTrueSkillMeanOldSM),
        player1H2HTrueSkillStandardDeviationOldSM: toNumber(data.player1H2HTrueSkillStandardDeviationOldSM),
        player2H2HTrueSkillMeanOldSM: toNumber(data.player2H2HTrueSkillMeanOldSM),
        player2H2HTrueSkillStandardDeviationOldSM: toNumber(data.player2H2HTrueSkillStandardDeviationOldSM),
        winProbabilityPlayer1H2HSM: toNumber(data.winProbabilityPlayer1H2HSM),
        player1H2HTrueSkillMeanOldGSM: toNumber(data.player1H2HTrueSkillMeanOldGSM),
        player1H2HTrueSkillStandardDeviationOldGSM: toNumber(data.player1H2HTrueSkillStandardDeviationOldGSM),
        player2H2HTrueSkillMeanOldGSM: toNumber(data.player2H2HTrueSkillMeanOldGSM),
        player2H2HTrueSkillStandardDeviationOldGSM: toNumber(data.player2H2HTrueSkillStandardDeviationOldGSM),
        winProbabilityPlayer1H2HGSM: toNumber(data.winProbabilityPlayer1H2HGSM),
        player1H2HTrueSkillMeanOldMS1: toNumber(data.player1H2HTrueSkillMeanOldMS1),
        player1H2HTrueSkillStandardDeviationOldMS1: toNumber(data.player1H2HTrueSkillStandardDeviationOldMS1),
        player2H2HTrueSkillMeanOldMS1: toNumber(data.player2H2HTrueSkillMeanOldMS1),
        player2H2HTrueSkillStandardDeviationOldMS1: toNumber(data.player2H2HTrueSkillStandardDeviationOldMS1),
        winProbabilityPlayer1H2HMS1: toNumber(data.winProbabilityPlayer1H2HMS1),
        player1H2HTrueSkillMeanOldSMS1: toNumber(data.player1H2HTrueSkillMeanOldSMS1),
        player1H2HTrueSkillStandardDeviationOldSMS1: toNumber(data.player1H2HTrueSkillStandardDeviationOldSMS1),
        player2H2HTrueSkillMeanOldSMS1: toNumber(data.player2H2HTrueSkillMeanOldSMS1),
        player2H2HTrueSkillStandardDeviationOldSMS1: toNumber(data.player2H2HTrueSkillStandardDeviationOldSMS1),
        winProbabilityPlayer1H2HSMS1: toNumber(data.winProbabilityPlayer1H2HSMS1),
        player1H2HTrueSkillMeanOldGSMS1: toNumber(data.player1H2HTrueSkillMeanOldGSMS1),
        player1H2HTrueSkillStandardDeviationOldGSMS1: toNumber(data.player1H2HTrueSkillStandardDeviationOldGSMS1),
        player2H2HTrueSkillMeanOldGSMS1: toNumber(data.player2H2HTrueSkillMeanOldGSMS1),
        player2H2HTrueSkillStandardDeviationOldGSMS1: toNumber(data.player2H2HTrueSkillStandardDeviationOldGSMS1),
        winProbabilityPlayer1H2HGSMS1: toNumber(data.winProbabilityPlayer1H2HGSMS1),
        player1H2HTrueSkillMeanOldMS2: toNumber(data.player1H2HTrueSkillMeanOldMS2),
        player1H2HTrueSkillStandardDeviationOldMS2: toNumber(data.player1H2HTrueSkillStandardDeviationOldMS2),
        player2H2HTrueSkillMeanOldMS2: toNumber(data.player2H2HTrueSkillMeanOldMS2),
        player2H2HTrueSkillStandardDeviationOldMS2: toNumber(data.player2H2HTrueSkillStandardDeviationOldMS2),
        winProbabilityPlayer1H2HMS2: toNumber(data.winProbabilityPlayer1H2HMS2),
        player1H2HTrueSkillMeanOldSMS2: toNumber(data.player1H2HTrueSkillMeanOldSMS2),
        player1H2HTrueSkillStandardDeviationOldSMS2: toNumber(data.player1H2HTrueSkillStandardDeviationOldSMS2),
        player2H2HTrueSkillMeanOldSMS2: toNumber(data.player2H2HTrueSkillMeanOldSMS2),
        player2H2HTrueSkillStandardDeviationOldSMS2: toNumber(data.player2H2HTrueSkillStandardDeviationOldSMS2),
        winProbabilityPlayer1H2HSMS2: toNumber(data.winProbabilityPlayer1H2HSMS2),
        player1H2HTrueSkillMeanOldGSMS2: toNumber(data.player1H2HTrueSkillMeanOldGSMS2),
        player1H2HTrueSkillStandardDeviationOldGSMS2: toNumber(data.player1H2HTrueSkillStandardDeviationOldGSMS2),
        player2H2HTrueSkillMeanOldGSMS2: toNumber(data.player2H2HTrueSkillMeanOldGSMS2),
        player2H2HTrueSkillStandardDeviationOldGSMS2: toNumber(data.player2H2HTrueSkillStandardDeviationOldGSMS2),
        winProbabilityPlayer1H2HGSMS2: toNumber(data.winProbabilityPlayer1H2HGSMS2),
        player1H2HTrueSkillMeanOldMS3: toNumber(data.player1H2HTrueSkillMeanOldMS3),
        player1H2HTrueSkillStandardDeviationOldMS3: toNumber(data.player1H2HTrueSkillStandardDeviationOldMS3),
        player2H2HTrueSkillMeanOldMS3: toNumber(data.player2H2HTrueSkillMeanOldMS3),
        player2H2HTrueSkillStandardDeviationOldMS3: toNumber(data.player2H2HTrueSkillStandardDeviationOldMS3),
        winProbabilityPlayer1H2HMS3: toNumber(data.winProbabilityPlayer1H2HMS3),
        player1H2HTrueSkillMeanOldSMS3: toNumber(data.player1H2HTrueSkillMeanOldSMS3),
        player1H2HTrueSkillStandardDeviationOldSMS3: toNumber(data.player1H2HTrueSkillStandardDeviationOldSMS3),
        player2H2HTrueSkillMeanOldSMS3: toNumber(data.player2H2HTrueSkillMeanOldSMS3),
        player2H2HTrueSkillStandardDeviationOldSMS3: toNumber(data.player2H2HTrueSkillStandardDeviationOldSMS3),
        winProbabilityPlayer1H2HSMS3: toNumber(data.winProbabilityPlayer1H2HSMS3),
        player1H2HTrueSkillMeanOldGSMS3: toNumber(data.player1H2HTrueSkillMeanOldGSMS3),
        player1H2HTrueSkillStandardDeviationOldGSMS3: toNumber(data.player1H2HTrueSkillStandardDeviationOldGSMS3),
        player2H2HTrueSkillMeanOldGSMS3: toNumber(data.player2H2HTrueSkillMeanOldGSMS3),
        player2H2HTrueSkillStandardDeviationOldGSMS3: toNumber(data.player2H2HTrueSkillStandardDeviationOldGSMS3),
        winProbabilityPlayer1H2HGSMS3: toNumber(data.winProbabilityPlayer1H2HGSMS3),
        player1H2HTrueSkillMeanOldMS4: toNumber(data.player1H2HTrueSkillMeanOldMS4),
        player1H2HTrueSkillStandardDeviationOldMS4: toNumber(data.player1H2HTrueSkillStandardDeviationOldMS4),
        player2H2HTrueSkillMeanOldMS4: toNumber(data.player2H2HTrueSkillMeanOldMS4),
        player2H2HTrueSkillStandardDeviationOldMS4: toNumber(data.player2H2HTrueSkillStandardDeviationOldMS4),
        winProbabilityPlayer1H2HMS4: toNumber(data.winProbabilityPlayer1H2HMS4),
        player1H2HTrueSkillMeanOldSMS4: toNumber(data.player1H2HTrueSkillMeanOldSMS4),
        player1H2HTrueSkillStandardDeviationOldSMS4: toNumber(data.player1H2HTrueSkillStandardDeviationOldSMS4),
        player2H2HTrueSkillMeanOldSMS4: toNumber(data.player2H2HTrueSkillMeanOldSMS4),
        player2H2HTrueSkillStandardDeviationOldSMS4: toNumber(data.player2H2HTrueSkillStandardDeviationOldSMS4),
        winProbabilityPlayer1H2HSMS4: toNumber(data.winProbabilityPlayer1H2HSMS4),
        player1H2HTrueSkillMeanOldGSMS4: toNumber(data.player1H2HTrueSkillMeanOldGSMS4),
        player1H2HTrueSkillStandardDeviationOldGSMS4: toNumber(data.player1H2HTrueSkillStandardDeviationOldGSMS4),
        player2H2HTrueSkillMeanOldGSMS4: toNumber(data.player2H2HTrueSkillMeanOldGSMS4),
        player2H2HTrueSkillStandardDeviationOldGSMS4: toNumber(data.player2H2HTrueSkillStandardDeviationOldGSMS4),
        winProbabilityPlayer1H2HGSMS4: toNumber(data.winProbabilityPlayer1H2HGSMS4),
        player1Streak: toNumber(data.player1Streak),
        player2Streak: toNumber(data.player2Streak),
        player1StreakS1: toNumber(data.player1StreakS1),
        player2StreakS1: toNumber(data.player2StreakS1),
        player1StreakS2: toNumber(data.player1StreakS2),
        player2StreakS2: toNumber(data.player2StreakS2),
        player1StreakS3: toNumber(data.player1StreakS3),
        player2StreakS3: toNumber(data.player2StreakS3),
        player1StreakS4: toNumber(data.player1StreakS4),
        player2StreakS4: toNumber(data.player2StreakS4),
        winProbabilityNN: toNumber(data.winProbabilityNN),
      };

      if (matchActive._id !== undefined) {
        batch.push(matchActive);
      }

      if (batch.length >= BATCH_SIZE) {
        await MatchActive.insertMany(batch, { ordered: false });
        totalInserted += batch.length;
        console.log(`✅ Inserted batch of ${batch.length} active matches (total so far: ${totalInserted})`);
        batch.length = 0;
      }
    }

    if (batch.length > 0) {
      await MatchActive.insertMany(batch, { ordered: false });
      totalInserted += batch.length;
      console.log(`✅ Inserted remaining ${batch.length} active matches (total: ${totalInserted})`);
    }

    console.log(`🎉 All active matches imported successfully. Final total: ${totalInserted}`);
  } catch (err) {
    console.error("❌ Import error:", err.message);
  } finally {
    await disconnect();
    console.log("🔌 Disconnected from DB");
  }
};

importMatchesActive();